# Generated by Django 5.2.8 on 2025-12-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeapp', '0002_notice_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='email',
            field=models.EmailField(default=None, max_length=254, unique=True),
        ),
    ]
