# Generated by Django 5.2.8 on 2026-01-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeapp', '0004_alter_students_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='notice_attachment',
            field=models.TextField(null=True),
        ),
    ]
