# Generated by Django 5.2.8 on 2026-01-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeapp', '0005_notice_notice_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='notice_attachment',
            field=models.TextField(),
        ),
    ]
