# Generated by Django 5.2.8 on 2026-01-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeapp', '0006_alter_notice_notice_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='sem',
            field=models.CharField(default='1', max_length=5),
        ),
    ]
