# Generated by Django 5.2.8 on 2026-01-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeapp', '0007_students_sem'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='sem',
            field=models.CharField(default='1', max_length=5),
        ),
    ]
