# Generated by Django 5.2.8 on 2026-02-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeapp', '0008_notice_sem'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
