# Generated by Django 5.2.8 on 2026-02-10 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeapp', '0009_notice_expired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='expired',
        ),
        migrations.AddField(
            model_name='notice',
            name='expired_date',
            field=models.DateTimeField(default=datetime.date(2026, 2, 13)),
        ),
    ]
