# Generated by Django 5.2.8 on 2026-02-10 11:56

import noticeapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeapp', '0010_remove_notice_expired_notice_expired_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='expired_date',
            field=models.DateTimeField(default=noticeapp.models.get_expire_date),
        ),
    ]
